Repository E3SM-Project/v3atm, pull requests merged in 2022-09, with the labels that each got.

#1 Change to use mpassi for F2010 and F20TR
  components/eam/cime_config/config_compsets.xml
Labels: compset

#3 Fix chemUCI high NOx
  components/eam/src/chemistry/mozart/mo_gas_phase_chemdr.F90
Labels: non-BFB

#5 Modify chemUCI mechanisms to meet thermal decomp reaction requirements
  components/eam/chem_proc/inputs/pp_chemUCI_linozv3_mam4_resus_mom_soag_tag.in
  components/eam/chem_proc/inputs/pp_chemUCI_mam4_resus_mom_soag.in
  components/eam/chem_proc/inputs/pp_chemUCI_mam4_resus_mom_soag_tag.in
  components/eam/chem_proc/inputs/pp_chemUCIfastj_linozv3_mam4_resus_mom_soag_tag.in
  components/eam/chem_proc/inputs/pp_chemUCIfastj_mam4_resus_mom_soag.in
Labels: non-BFB

#7 Add v3atm developer and integration test suites
  cime_config/config_grids.xml
  cime_config/tests.py
  components/eam/bld/namelist_files/use_cases/20TR_eam_chemUCI-Linoz.xml
  components/eam/cime_config/testdefs/testmods_dirs/eam/20tr_v3atm/README
  components/eam/cime_config/testdefs/testmods_dirs/eam/20tr_v3atm/user_nl_elm
  components/eam/cime_config/testdefs/testmods_dirs/eam/20tr_v3atm_cosplite/README
  components/eam/cime_config/testdefs/testmods_dirs/eam/20tr_v3atm_cosplite/shell_commands
  components/eam/cime_config/testdefs/testmods_dirs/eam/20tr_v3atm_cosplite/user_nl_eam
  components/eam/cime_config/testdefs/testmods_dirs/eam/20tr_v3atm_cosplite/user_nl_elm
  components/eam/cime_config/testdefs/testmods_dirs/eam/20tr_v3atm_rtmoff/README
  components/eam/cime_config/testdefs/testmods_dirs/eam/20tr_v3atm_rtmoff/user_nl_elm
  components/eam/cime_config/testdefs/testmods_dirs/eam/20tr_v3atm_rtmoff/user_nl_mosart
  components/elm/bld/namelist_files/namelist_defaults.xml
Labels: BFB

#8 Update cori-knl machine file
  cime_config/machines/config_machines.xml
Labels: BFB

#16 Revised v2atm developer and integration test suites
  cime_config/tests.py
Labels: BFB

#17 A revised handling of cflx as a stealth feature
  components/eam/bld/namelist_files/namelist_definition.xml
  components/eam/src/cpl/atm_import_export.F90
  components/eam/src/physics/cam/cflx.F90
  components/eam/src/physics/cam/clubb_intr.F90
  components/eam/src/physics/cam/phys_control.F90
  components/eam/src/physics/cam/physpkg.F90
  components/eam/src/physics/cam/restart_physics.F90
Labels: enhancement, BFB
