Repository E3SM-Project/v3atm, pull requests merged in 2022-10, with the labels that each got.

#9 Yfenganl/atm/chem uci chem mzt mosaic dustemis k14 amip
  components/eam/bld/namelist_files/namelist_defaults_eam.xml
  components/eam/src/chemistry/modal_aero/dust_model.F90
  components/eam/src/chemistry/mozart/mo_gas_phase_chemdr.F90
  components/elm/src/biogeochem/DUSTMod.F90
Labels: non-BFB

#15 Link MOSAIC nitrate and MAM5 strat sulfate treatment
  components/eam/bld/build-namelist
  components/eam/bld/configure
  components/eam/chem_proc/inputs/pp_chemUCI_linozv3_mam4_resus_mom_soag_mosaic_tag.in
  components/eam/chem_proc/inputs/pp_chemUCI_linozv3_mam5_resus_mom_soag_tag_cnst_no3_oh_mosaic.in
  components/eam/src/chemistry/modal_aero/aero_model.F90
  components/eam/src/chemistry/modal_aero/dust_model.F90
  components/eam/src/chemistry/modal_aero/modal_aero_amicphys.F90
  components/eam/src/chemistry/modal_aero/modal_aero_coag.F90
  components/eam/src/chemistry/modal_aero/modal_aero_data.F90
  components/eam/src/chemistry/modal_aero/modal_aero_initialize_data.F90
  components/eam/src/chemistry/modal_aero/seasalt_model.F90
  components/eam/src/chemistry/modal_aero/sox_cldaero_mod.F90
  components/eam/src/chemistry/utils/prescribed_volcaero.F90
  components/eam/src/physics/cam/hetfrz_classnuc_cam.F90
  components/eam/src/physics/cam/modal_aer_opt.F90
  components/eam/src/physics/cam/nucleate_ice_cam.F90
  components/eam/src/physics/cam/rad_constituents.F90
Labels: BFB

#12 Add P3 as the microphysics scheme
  components/eam/bld/build-namelist
  components/eam/bld/config_files/definition.xml
  components/eam/bld/configure
  components/eam/bld/namelist_files/namelist_defaults_eam.xml
  components/eam/bld/namelist_files/namelist_definition.xml
  components/eam/cime_config/config_component.xml
  components/eam/cime_config/config_compsets.xml
  components/eam/src/chemistry/mozart/chemistry.F90
  components/eam/src/chemistry/mozart/mo_gas_phase_chemdr.F90
  components/eam/src/physics/cam/check_energy.F90
  components/eam/src/physics/cam/cloud_diagnostics.F90
  components/eam/src/physics/cam/debug_info.F90
  components/eam/src/physics/cam/micro_p3.F90
  components/eam/src/physics/cam/micro_p3_interface.F90
  components/eam/src/physics/cam/micro_p3_utils.F90
  components/eam/src/physics/cam/microp_driver.F90
  components/eam/src/physics/cam/phys_control.F90
  components/eam/src/physics/cam/physics_utils.F90
  components/eam/src/physics/cam/physpkg.F90
  components/eam/src/physics/cam/radiation_data.F90
  components/eam/src/physics/cam/scream_abortutils.F90
  components/eam/src/physics/cam/wv_sat_scream.F90
Labels: CC

#14 Add ZM enhancement to v3atm branch
  components/eam/bld/build-namelist
  components/eam/bld/namelist_files/namelist_defaults_eam.xml
  components/eam/bld/namelist_files/namelist_definition.xml
  components/eam/src/physics/cam/activate_drop_mam.F90
  components/eam/src/physics/cam/clubb_intr.F90
  components/eam/src/physics/cam/conv_water.F90
  components/eam/src/physics/cam/convect_deep.F90
  components/eam/src/physics/cam/convect_shallow.F90
  components/eam/src/physics/cam/macrop_driver.F90
  components/eam/src/physics/cam/ndrop.F90
  components/eam/src/physics/cam/ndrop_bam.F90
  components/eam/src/physics/cam/nucleate_ice_conv.F90
  components/eam/src/physics/cam/physpkg.F90
  components/eam/src/physics/cam/zm_conv.F90
  components/eam/src/physics/cam/zm_conv_intr.F90
  components/eam/src/physics/cam/zm_microphysics.F90
Labels: enhancement, BFB

#23 Quick fix for non-BFB results when all ZM enhancements are turned off
  components/eam/bld/build-namelist
  components/eam/bld/namelist_files/namelist_defaults_eam.xml
  components/eam/src/physics/cam/conv_water.F90
  components/eam/src/physics/cam/zm_conv.F90
  components/eam/src/physics/cam/zm_conv_intr.F90
Labels: bug fix PR

#22 Add VBS SOA and couple it with chemUCI
  components/eam/bld/build-namelist
  components/eam/bld/config_files/definition.xml
  components/eam/bld/configure
  components/eam/bld/namelist_files/master_gas_drydep_list.xml
  components/eam/bld/namelist_files/master_gas_wetdep_list.xml
  components/eam/chem_proc/inputs/pp_chemUCI_linozv3_mam4_resus_mom_vbs_tag.in
  components/eam/src/chemistry/modal_aero/modal_aero_amicphys.F90
  components/eam/src/chemistry/modal_aero/modal_aero_data.F90
  components/eam/src/chemistry/mozart/mo_gas_phase_chemdr.F90
  components/eam/src/chemistry/mozart/mo_neu_wetdep.F90
  components/eam/src/chemistry/mozart/mo_sethet.F90
  components/eam/src/physics/cam/modal_aer_opt.F90
  components/eam/src/physics/cam/phys_control.F90
Labels: BFB

#25 Change to output in-cloud properties to after the cloud microphysics
  components/eam/src/physics/cam/micro_p3_interface.F90
Labels: non-BFB
